FROM ubuntu:18.04

LABEL maintainer service@fisco.com.cn
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update && apt-get install -qy --no-install-recommends \
    git clang build-essential cmake libssl-dev zlib1g-dev ca-certificates \
    && export DEBIAN_FRONTEND=noninteractive \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt-get install -qy --no-install-recommends tzdata \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm  -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://oauth2:15cu-VPcCbmEjzW9hgCx@git.iflytek.com/TC_FLYBC/FISCO-BCOS.git && cd FISCO-BCOS \
    && cmake . && make -j2 && cp -r ./deps /deps && cd .. && rm -rf FISCO-BCOS